### ISSUE TITLE
Special Zombie mode for a short period of time

### ISSUE THREAD

**Issue by Haox09** [deferred-impact/battledudes-issue-tracker#139]
Zombie mode is a interesting idea, but it will take a long time to create because of its difference to all the other gamemodes. It will be selected, like the other gammodes, at the end of each game. At the start of game 1-3 (what number is adequete I don't know) are spawned as zombies. Zombies are teammates, and all humans are on the same team. Zombies will be hatless and have the color of green skin below. Their melee will be fist. As you all hopefully know, they infect the humans and the humans will join them. The zombies will have a boosted speed(like added in sprinter perk) and faster regen than normal player. One hit is enough to kill and infect a human. At the end of the time if there's more human than zombies, human win. If there's less human than the zombies or all human have been infected, zombie win. The later infected will of course recieve less award at the end of the game than the original infected, other variable is infect count. Human award also vary on zombs kills and if they won the game or not.
![image](https://user-images.githubusercontent.com/117471088/223206201-957e7950-2dbd-4d8a-9963-0a3a1c615f17.png)

**Comment by deferred-impact** [comment]
I see some issues with this gamemode as proposed:
 - one hit kill melee with sprinter on top is an incredibly powerful combo. Doubly so if you consider that death for zombies is almost non-consequential, so the correct play is always to try and rush the enemy. It's weird, but you somehow managed to make the zombies OP instead of the people with guns
 - the scoring system as proposed has the same issue as the scoring in Payload (#129) as it results in situations where the game is not over, but the winner has already been decided. Specifically, if there are more zombies than humans, there is no point to fight anymore - the human team already lost

But i also see some issues with this gamemode in general, which i doubt could be solved:
 - i'm a rocket main. You are adding yet another gamemode where i don't get to use my gun (or any guns, for that matter). I don't like it.
 - this gamemode has a very heavy snowball effect, perhaps intentionally. But that is not good. If your team is bad, be it zombies or humans, it will remain (if zombies) or very soon end up (if humans) completely outnumbered. No other team gamemode right now (intentionally) sets up unbalanced teams. And be honest: do you enjoy fighting in a 1v5 fight?
 - being asymmetrical, it's a balancing nightmare. Other gamemodes auto-balance themselves by the fact that both teams have exactly the same equipment, and in most other modes, the same goal as well. Here, though, you'd constantly have to deal with complaints that "zombies need a buff", "zombies need a nerf", "wtf why is melee instant kill", "ban humans from equipping HeavySniper!" et cetera. Do you trust our incredibly active dev to handle the balancing correctly?

As such, i do not see it as a viable addition to the game.

But perhaps we could devise a better alternative? I could try, but i will be honest, at the end of the day, i just don't understand the appeal of zombies gamemode at all. (Yes, i am biased and i don't care.) If you could explain to me what is good about this gamemode, perhaps we could adjust the scenario to preserve the good and address the bad.

**Comment by Gregory-Y** [comment]
I would suggest the following to improve it:

- making the zombies use fists or melee, but only deal normal fist/melee damage, don't make it 1 hit kill because if a human reloads at the wrong time or have a lag spike that would be very unepic.
- make the first 1 or 2 zombies have twice the amount of health of a regular player, so 104 health. That way early game is a bit easier for zombies. After the number of zombies becomes greater than the number of humans, this bonus disappears (after the patient zero's next death).
- Make it so that humans can gain bonuses after killing zombies, so 20 kills for example gives them a health bonus or something. That way humans have a slightly better chance late-game.

**Comment by deferred-impact** [comment]
@NOTGregory , okay, that... *kind of* addresses the snowball effect, but it is a problematic solution. All you're doing is countering one snowball (humans die, join the other team) with another snowball (humans kill, become stronger). I'm not saying it cannot work; of course it would work if you balance it correctly. The trouble is balancing it correctly.

I've been thinking about it for a couple of minutes here. Perhaps the better solution would be to integrate respawns into such a mode. Now, it's not at all clear how to do that, but here's my proposal:

Each team has a number of "slots". The exact ratio of slots is the thing we get to balance; more slots on a team, more players on a team, stronger team. Let's say we start with 7 human slots and 13 zombie slots.

If a player dies and there are slots on the opposing team, they get to switch to that team. So if a human dies, and there aren't enough zombies, the human who just died will switch to the team of zombies. If a zombie dies, it swaps to the human team if possible.

It doesn't necessarily make "sense" in terms of lore (why can zombies regain humanity..? Perhaps instead of zombies, some kind of "corruption" lore would be necessary), but it is quite elegant, in my opinion. The game remains balanced throughout the entire match, whilst we still get to experience a small team of heavy armed dudes battle against a horde of melee rushers.

The other issue with this idea is that good players would rarely get to swap teams (because good players don't die often). Noobs would be the ones who get to swap teams often. I'm not sure if there is a way to address this. But perhaps it's fine?

We could give players who play well a higher "priority" when choosing which player to switch (i.e. 1 human is dead and 5 zombies is dead, which zombie do we swap with the human?) E.g. higher kills = higher switch priority. It may also be wise to extend the respawn timer, to something like 20 seconds, so that there is more chance for overlapping deaths.
