### ISSUE TITLE
Stealing enemy specials.

### ISSUE THREAD

**Issue by Gregory-Y** [deferred-impact/battledudes-issue-tracker#80]
Yes, you heard me right, I want a mechanic that allows you to steal an enemy medkit or ammo box. You simply walk up to one and press "e" or another key to abscond with the special. Now, what I'm not sure about is what should happen once you steal it. Do you gain a health bonus or regain all your ammo? Or does the special go into another slot in your inventory so that you can place it down?

**Comment by deferred-impact** [comment]
I don't hate this idea (although my preferred implementation slightly differs), but really before we discuss the implementation, we must address the elephant in the room - how to prevent griefing?

Plenty of people act friendly in team modes right now. Currently it's not that big of a deal, because the extent of their impact is, they're not dealing damage to enemies. Which is unfortunate, but having a single friendly on your team is the same as having a single noob on your team who has no idea how to play. It happens often and usually doesn't impact the outcome much. And when it does, well, you can't really blame them.

Now what if that friendly decided to team up with an enemy and follow them around with a medkit? Now, they're actively griefing. You shoot the guy, and your """teammate""" drops a medkit **for them**, and they consume it. Your damage is instantly gone. This is quite problematic, wouldn't you agree?

**Comment by Gregory-Y** [comment]
Never considered that...

**Comment by Gregory-Y** [comment]
Gonna close this since it's a bad idea.

**Comment by deferred-impact** [comment]
Ok but close it as not planned ffs
